import { MigrationInterface, QueryRunner } from "typeorm";

export class migraSetiembre1661882608864 implements MigrationInterface {
    name = 'migraSetiembre1661882608864'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`permission\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`parent_menu\` varchar(255) NULL, \`parent_id\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`alias\` varchar(255) NULL, \`url\` varchar(255) NULL, \`icon\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`name\` varchar(50) NOT NULL, \`description\` varchar(100) NULL, \`status\` tinyint NULL DEFAULT '1', INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), UNIQUE INDEX \`name_deleted\` (\`name\`, \`deleted_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`email\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`mobile\` varchar(11) NULL, \`password\` varchar(100) NOT NULL, \`name\` varchar(255) NULL, \`profile_photo\` varchar(255) NULL, \`created_by\` char(36) NULL, \`updated_by\` char(36) NULL, \`activation_link\` varchar(255) NOT NULL, \`is_activated\` tinyint NOT NULL DEFAULT 0, \`role_id\` bigint NULL COMMENT 'Generar ID', INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`username\`), INDEX \`IDX_29fd51e9cf9241d022c5a4e02e\` (\`mobile\`), UNIQUE INDEX \`mobile_deleted\` (\`mobile\`, \`deleted_at\`), UNIQUE INDEX \`email_deleted\` (\`email\`, \`deleted_at\`), UNIQUE INDEX \`username_deleted\` (\`username\`, \`deleted_at\`), UNIQUE INDEX \`username_mobile_email_unique\` (\`username\`, \`mobile\`, \`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_involucrado_sector\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_involucrado_natural\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`paterno\` varchar(50) NOT NULL, \`materno\` varchar(50) NOT NULL, \`nombre\` varchar(50) NOT NULL, \`nro_documento\` varchar(8) NOT NULL, \`telefono\` varchar(10) NOT NULL, \`celular1\` varchar(9) NOT NULL, \`celular2\` varchar(9) NOT NULL, \`direccion\` varchar(150) NOT NULL, \`correo\` varchar(100) NOT NULL, \`tipo_documento_id\` bigint NULL COMMENT 'Generar ID', UNIQUE INDEX \`nro_documento\` (\`nro_documento\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_documento_tipo\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`codigo\` varchar(2) NOT NULL, \`abreviatura\` varchar(20) NOT NULL, \`nombre\` varchar(50) NOT NULL, \`longitud\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_involucrado_juridico\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`razon_social\` varchar(150) NOT NULL, \`nro_documento\` varchar(11) NOT NULL, \`telefono\` varchar(10) NOT NULL, \`direccion\` varchar(150) NOT NULL, \`correo\` varchar(100) NOT NULL, \`tipo_documento_id\` bigint NULL COMMENT 'Generar ID', \`sector_id\` bigint NULL COMMENT 'Generar ID', \`clasificacion_id\` bigint NULL COMMENT 'Generar ID', UNIQUE INDEX \`nro_documento\` (\`nro_documento\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_involucrado_clasificacion\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`coor_coordinacion_estado\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_desglose\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(20) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`area\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_tipo_cotizacion\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`name\` varchar(50) NOT NULL, INDEX \`IDX_e778b09caf58856348d16e46b4\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cotizacion\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`codigo\` bigint NOT NULL, \`nro_informes\` tinyint NOT NULL, \`actualizacion\` tinyint NOT NULL DEFAULT 0, \`adjunto\` varchar(255) NOT NULL, \`fecha_solicitud\` timestamp NULL, \`fecha_envio_cliente\` timestamp NULL, \`fecha_finalizacion\` timestamp NULL, \`vendedor_id\` int NOT NULL, \`orden_servicio\` varchar(50) NULL, \`orden_servicio_adjunto\` varchar(100) NULL, \`plazo\` tinyint NOT NULL, \`motivo\` varchar(50) NULL, \`tipo_perito\` tinyint NOT NULL, \`perito_id\` tinyint NOT NULL, \`perito_costo\` decimal(10,2) NOT NULL DEFAULT '0.00', \`datos_adicionales\` varchar(100) NULL, \`desglose_id\` int NOT NULL, INDEX \`IDX_ee4019c5e35bb7689603768198\` (\`codigo\`), INDEX \`IDX_ae532c7d0d7328aaef83afe873\` (\`vendedor_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_cotizacion_estado\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(15) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_access\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`role_id\` int NOT NULL COMMENT '角色id', \`access_id\` int NOT NULL COMMENT '资源id', \`type\` tinyint NOT NULL COMMENT '资源类型:2:表示菜单,3:表示接口(API)', UNIQUE INDEX \`role_access_type_deleted\` (\`role_id\`, \`access_id\`, \`type\`, \`deleted_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_moneda\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`codigo\` varchar(3) NOT NULL, \`simbolo\` varchar(10) NOT NULL, \`nombre\` varchar(25) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_has_role\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`role_id\` int NOT NULL COMMENT '角色id', \`access_id\` int NOT NULL COMMENT '资源id', \`type\` tinyint NOT NULL COMMENT '资源类型:2:表示菜单,3:表示接口(API)', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_servicio_tipo\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_servicio\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(60) NOT NULL, \`tipo_servicio_id\` bigint NULL COMMENT 'Generar ID', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_requisito\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(100) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_cotizacion_tipo\` (\`id\` bigint NOT NULL AUTO_INCREMENT COMMENT 'Generar ID', \`created_at\` timestamp(6) NOT NULL COMMENT 'Fecha de creación' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL COMMENT 'Fecha de Actualización' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL COMMENT 'Fecha de Borrado', \`nombre\` varchar(20) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`refresh_token\` text NOT NULL, \`user_id\` bigint NULL COMMENT 'Generar ID', UNIQUE INDEX \`REL_e50ca89d635960fda2ffeb1763\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission_roles_role\` (\`permission_id\` bigint NOT NULL, \`role_id\` bigint NOT NULL, INDEX \`IDX_cb69995e8fe1b66e77d14b1ed7\` (\`permission_id\`), INDEX \`IDX_3a48b2836b84db15061bcef0a3\` (\`role_id\`), PRIMARY KEY (\`permission_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permission\` (\`role_id\` bigint NOT NULL, \`permission_id\` bigint NOT NULL, INDEX \`IDX_3d0a7155eafd75ddba5a701336\` (\`role_id\`), INDEX \`IDX_e3a3ba47b7ca00fd23be4ebd6c\` (\`permission_id\`), PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`co_requisito_servicio_detalle\` (\`servicioId\` bigint NOT NULL, \`requisitoId\` bigint NOT NULL, INDEX \`IDX_8a6fae70330caa0bf20b4cf8fc\` (\`servicioId\`), INDEX \`IDX_23fc8866e66eb1d8088958d2ab\` (\`requisitoId\`), PRIMARY KEY (\`servicioId\`, \`requisitoId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` ADD \`nombre\` varchar(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` ADD \`name\` varchar(50) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_5b9f191bc56a815beca5ed70d6\` ON \`co_desglose\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_fb2e442d14add3cefbdf33c4561\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_natural\` ADD CONSTRAINT \`FK_f331110ce88fe4bcc96f4c5e741\` FOREIGN KEY (\`tipo_documento_id\`) REFERENCES \`co_documento_tipo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` ADD CONSTRAINT \`FK_21ca1157c54ce5362bc7aa3c9c0\` FOREIGN KEY (\`tipo_documento_id\`) REFERENCES \`co_documento_tipo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` ADD CONSTRAINT \`FK_2f284a2dafd0fd606de7f39cff1\` FOREIGN KEY (\`sector_id\`) REFERENCES \`co_involucrado_sector\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` ADD CONSTRAINT \`FK_85ec900cb51d4fe2068b00cfee7\` FOREIGN KEY (\`clasificacion_id\`) REFERENCES \`co_involucrado_clasificacion\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_servicio\` ADD CONSTRAINT \`FK_b5d97a883faa5b1abe31aca36f2\` FOREIGN KEY (\`tipo_servicio_id\`) REFERENCES \`co_servicio_tipo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`token\` ADD CONSTRAINT \`FK_e50ca89d635960fda2ffeb17639\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permission_roles_role\` ADD CONSTRAINT \`FK_cb69995e8fe1b66e77d14b1ed7c\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permission\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`permission_roles_role\` ADD CONSTRAINT \`FK_3a48b2836b84db15061bcef0a3d\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permission\` ADD CONSTRAINT \`FK_3d0a7155eafd75ddba5a7013368\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permission\` ADD CONSTRAINT \`FK_e3a3ba47b7ca00fd23be4ebd6cf\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`co_requisito_servicio_detalle\` ADD CONSTRAINT \`FK_8a6fae70330caa0bf20b4cf8fc7\` FOREIGN KEY (\`servicioId\`) REFERENCES \`co_servicio\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`co_requisito_servicio_detalle\` ADD CONSTRAINT \`FK_23fc8866e66eb1d8088958d2ab2\` FOREIGN KEY (\`requisitoId\`) REFERENCES \`co_requisito\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`co_requisito_servicio_detalle\` DROP FOREIGN KEY \`FK_23fc8866e66eb1d8088958d2ab2\``);
        await queryRunner.query(`ALTER TABLE \`co_requisito_servicio_detalle\` DROP FOREIGN KEY \`FK_8a6fae70330caa0bf20b4cf8fc7\``);
        await queryRunner.query(`ALTER TABLE \`role_permission\` DROP FOREIGN KEY \`FK_e3a3ba47b7ca00fd23be4ebd6cf\``);
        await queryRunner.query(`ALTER TABLE \`role_permission\` DROP FOREIGN KEY \`FK_3d0a7155eafd75ddba5a7013368\``);
        await queryRunner.query(`ALTER TABLE \`permission_roles_role\` DROP FOREIGN KEY \`FK_3a48b2836b84db15061bcef0a3d\``);
        await queryRunner.query(`ALTER TABLE \`permission_roles_role\` DROP FOREIGN KEY \`FK_cb69995e8fe1b66e77d14b1ed7c\``);
        await queryRunner.query(`ALTER TABLE \`token\` DROP FOREIGN KEY \`FK_e50ca89d635960fda2ffeb17639\``);
        await queryRunner.query(`ALTER TABLE \`co_servicio\` DROP FOREIGN KEY \`FK_b5d97a883faa5b1abe31aca36f2\``);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` DROP FOREIGN KEY \`FK_85ec900cb51d4fe2068b00cfee7\``);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` DROP FOREIGN KEY \`FK_2f284a2dafd0fd606de7f39cff1\``);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_juridico\` DROP FOREIGN KEY \`FK_21ca1157c54ce5362bc7aa3c9c0\``);
        await queryRunner.query(`ALTER TABLE \`co_involucrado_natural\` DROP FOREIGN KEY \`FK_f331110ce88fe4bcc96f4c5e741\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_fb2e442d14add3cefbdf33c4561\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b9f191bc56a815beca5ed70d6\` ON \`co_desglose\``);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` DROP COLUMN \`nombre\``);
        await queryRunner.query(`ALTER TABLE \`co_desglose\` ADD \`nombre\` varchar(20) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_23fc8866e66eb1d8088958d2ab\` ON \`co_requisito_servicio_detalle\``);
        await queryRunner.query(`DROP INDEX \`IDX_8a6fae70330caa0bf20b4cf8fc\` ON \`co_requisito_servicio_detalle\``);
        await queryRunner.query(`DROP TABLE \`co_requisito_servicio_detalle\``);
        await queryRunner.query(`DROP INDEX \`IDX_e3a3ba47b7ca00fd23be4ebd6c\` ON \`role_permission\``);
        await queryRunner.query(`DROP INDEX \`IDX_3d0a7155eafd75ddba5a701336\` ON \`role_permission\``);
        await queryRunner.query(`DROP TABLE \`role_permission\``);
        await queryRunner.query(`DROP INDEX \`IDX_3a48b2836b84db15061bcef0a3\` ON \`permission_roles_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_cb69995e8fe1b66e77d14b1ed7\` ON \`permission_roles_role\``);
        await queryRunner.query(`DROP TABLE \`permission_roles_role\``);
        await queryRunner.query(`DROP INDEX \`REL_e50ca89d635960fda2ffeb1763\` ON \`token\``);
        await queryRunner.query(`DROP TABLE \`token\``);
        await queryRunner.query(`DROP TABLE \`co_cotizacion_tipo\``);
        await queryRunner.query(`DROP TABLE \`co_requisito\``);
        await queryRunner.query(`DROP TABLE \`co_servicio\``);
        await queryRunner.query(`DROP TABLE \`co_servicio_tipo\``);
        await queryRunner.query(`DROP TABLE \`user_has_role\``);
        await queryRunner.query(`DROP TABLE \`co_moneda\``);
        await queryRunner.query(`DROP INDEX \`role_access_type_deleted\` ON \`role_access\``);
        await queryRunner.query(`DROP TABLE \`role_access\``);
        await queryRunner.query(`DROP TABLE \`co_cotizacion_estado\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae532c7d0d7328aaef83afe873\` ON \`cotizacion\``);
        await queryRunner.query(`DROP INDEX \`IDX_ee4019c5e35bb7689603768198\` ON \`cotizacion\``);
        await queryRunner.query(`DROP TABLE \`cotizacion\``);
        await queryRunner.query(`DROP INDEX \`IDX_e778b09caf58856348d16e46b4\` ON \`co_tipo_cotizacion\``);
        await queryRunner.query(`DROP TABLE \`co_tipo_cotizacion\``);
        await queryRunner.query(`DROP TABLE \`area\``);
        await queryRunner.query(`DROP TABLE \`co_desglose\``);
        await queryRunner.query(`DROP TABLE \`coor_coordinacion_estado\``);
        await queryRunner.query(`DROP TABLE \`co_involucrado_clasificacion\``);
        await queryRunner.query(`DROP INDEX \`nro_documento\` ON \`co_involucrado_juridico\``);
        await queryRunner.query(`DROP TABLE \`co_involucrado_juridico\``);
        await queryRunner.query(`DROP TABLE \`co_documento_tipo\``);
        await queryRunner.query(`DROP INDEX \`nro_documento\` ON \`co_involucrado_natural\``);
        await queryRunner.query(`DROP TABLE \`co_involucrado_natural\``);
        await queryRunner.query(`DROP TABLE \`co_involucrado_sector\``);
        await queryRunner.query(`DROP INDEX \`username_mobile_email_unique\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`username_deleted\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`email_deleted\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`mobile_deleted\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_29fd51e9cf9241d022c5a4e02e\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`name_deleted\` ON \`role\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
    }

}
